### ISSUE TITLE
Can not submit tx by Ledger hardware wallet

### ISSUE THREAD

**Issue by EasonTheJolter** [astroport-fi/asteroid-protocol#55]
I checked your code, you use `keplr.getOfflineSigner` as the signer
hardware wallet required using `keplr.getOfflineSignerOnlyAmino`
plus, the message of tx contains image file base64, this is a huge length of data for the hardware wallet, and it will also result in failing to submit the tx
I use a hardware wallet for security, hope you can fix this bug soon

![inscription-ledger](https://github.com/astroport-fi/asteroid-protocol/assets/151594068/bd625494-5a1e-45c6-a34b-8933d9f8c233)

**Comment by donovansolms** [comment]
Hi, there is currently no fix possible for this since it is the only way to get larger content inscriptions on chain. There is a possible fix coming to Cosmos SDK 0.50 called `SIGN_MODE_TEXTUAL`. Whether this will work with hardware wallets due to the size of images remains to be seen. We are working on fixing this for non-inscription transactions (such as transfer, mint, etc)
